version: "3.9"

services:
  schpk_bot:
#    build: ./bot/
    env_file:
      - env_vars/sch_pk.env
    image: aashushpanov/my_repo:school_mentor_bot
    container_name: mentor_bot_pk
    networks:
      - postgres
      
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${email}
      PGADMIN_DEFAULT_PASSWORD: "${password_pg}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres


networks:
  postgres:
    driver: bridge